name: Run Spectral on Pull Requests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string


jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest

    steps:
      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'example/v3.0/patstore.yaml'
          spectral_ruleset: 'https://raw.githubusercontent.com/trimble-oss/openapi-spectral-rules/main/spectral.yaml'
